### ISSUE TITLE
Mixin Error: `mixin apply failed mixins.customfishing.json:MixinNetHandlerPlayClient`

### ISSUE THREAD

**Issue by Krutoy242** [ukmojb/CustomFishing#2]
After installing CustomFishing onto [E2EE](https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended) modpack, i found this error in debug.log file:

```ruby
[Client thread/WARN] [mixin]: Mixin apply for mod unknown-owner failed mixins.customfishing.json:MixinNetHandlerPlayClient from mod unknown-owner -> net.minecraft.client.network.NetHandlerPlayClient: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Invalid descriptor on mixins.customfishing.json:MixinNetHandlerPlayClient from mod unknown-owner->@Inject::handleSpawnObject(Lnet/minecraft/network/play/server/SPacketSpawnObject;)V! Expected (Lnet/minecraft/network/play/server/SPacketSpawnObject;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lnet/minecraft/network/play/server/SPacketSpawnObject;)V [ -> Inject -> mixins.customfishing.json:MixinNetHandlerPlayClient from mod unknown-owner->@Inject::handleSpawnObject(Lnet/minecraft/network/play/server/SPacketSpawnObject;)V]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on mixins.customfishing.json:MixinNetHandlerPlayClient from mod unknown-owner->@Inject::handleSpawnObject(Lnet/minecraft/network/play/server/SPacketSpawnObject;)V! Expected (Lnet/minecraft/network/play/server/SPacketSpawnObject;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lnet/minecraft/network/play/server/SPacketSpawnObject;)V [ -> Inject -> mixins.customfishing.json:MixinNetHandlerPlayClient from mod unknown-owner->@Inject::handleSpawnObject(Lnet/minecraft/network/play/server/SPacketSpawnObject;)V]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:559) ~[sponge-mixin-0.20.6+mixin.0.8.7.jar:0.20.6+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:489) ~[sponge-mixin-0.20.6+mixin.0.8.7.jar:0.20.6+mixin.0.8.7]
[...]
```

Usually such warnings means that mixin is not working.
What functionality not working? How to fix that?

[debug.log](https://github.com/user-attachments/files/17003013/debug.log)

**Comment by ukmojb** [comment]
Fixed at 0.0.6）））
I forgot to add @author

**Comment by Krutoy242** [comment]
No, this error is not fixed in `0.0.6` and still appear in log file:

```ruby
[13:11:24] [Client thread/WARN] [mixin]: Mixin apply for mod unknown-owner failed mixins.customfishing.json:MixinNetHandlerPlayClient from mod unknown-owner -> net.minecraft.client.network.NetHandlerPlayClient: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Invalid descriptor on mixins.customfishing.json:MixinNetHandlerPlayClient from mod unknown-owner->@Inject::handleSpawnObject(Lnet/minecraft/network/play/server/SPacketSpawnObject;)V! Expected (Lnet/minecraft/network/play/server/SPacketSpawnObject;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lnet/minecraft/network/play/server/SPacketSpawnObject;)V [ -> Inject -> mixins.customfishing.json:MixinNetHandlerPlayClient from mod unknown-owner->@Inject::handleSpawnObject(Lnet/minecraft/network/play/server/SPacketSpawnObject;)V]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on mixins.customfishing.json:MixinNetHandlerPlayClient from mod unknown-owner->@Inject::handleSpawnObject(Lnet/minecraft/network/play/server/SPacketSpawnObject;)V! Expected (Lnet/minecraft/network/play/server/SPacketSpawnObject;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lnet/minecraft/network/play/server/SPacketSpawnObject;)V [ -> Inject -> mixins.customfishing.json:MixinNetHandlerPlayClient from mod unknown-owner->@Inject::handleSpawnObject(Lnet/minecraft/network/play/server/SPacketSpawnObject;)V]
```

[debug.log](https://github.com/user-attachments/files/17012668/debug.log)

**Comment by ukmojb** [comment]
> No, this error is not fixed in `0.0.6` and still appear in log file:
> 
> ```ruby
> [13:11:24] [Client thread/WARN] [mixin]: Mixin apply for mod unknown-owner failed mixins.customfishing.json:MixinNetHandlerPlayClient from mod unknown-owner -> net.minecraft.client.network.NetHandlerPlayClient: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Invalid descriptor on mixins.customfishing.json:MixinNetHandlerPlayClient from mod unknown-owner->@Inject::handleSpawnObject(Lnet/minecraft/network/play/server/SPacketSpawnObject;)V! Expected (Lnet/minecraft/network/play/server/SPacketSpawnObject;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lnet/minecraft/network/play/server/SPacketSpawnObject;)V [ -> Inject -> mixins.customfishing.json:MixinNetHandlerPlayClient from mod unknown-owner->@Inject::handleSpawnObject(Lnet/minecraft/network/play/server/SPacketSpawnObject;)V]
> org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on mixins.customfishing.json:MixinNetHandlerPlayClient from mod unknown-owner->@Inject::handleSpawnObject(Lnet/minecraft/network/play/server/SPacketSpawnObject;)V! Expected (Lnet/minecraft/network/play/server/SPacketSpawnObject;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lnet/minecraft/network/play/server/SPacketSpawnObject;)V [ -> Inject -> mixins.customfishing.json:MixinNetHandlerPlayClient from mod unknown-owner->@Inject::handleSpawnObject(Lnet/minecraft/network/play/server/SPacketSpawnObject;)V]
> ```
> 
> [debug.log](https://github.com/user-attachments/files/17012668/debug.log)

emmmm..
Let me check again,wait some minutes

**Comment by ukmojb** [comment]
I solved this problem, but found out that the fish hook will not be rendered when the player throws the fishing rod in the server, but the fish hook is present on the server, so only fish particles will appear, I need more time to solve it))))))

**Comment by ukmojb** [comment]
Sorry, I failed, I tried a lot of things but the problem still exists, the client is fine, but when the player joins the server they can't see the hook... (But the fish hook is normal on the server, the fish hook only does not exist on the client, the fish particle still exists)

**Comment by Krutoy242** [comment]
Then i will wait for the fix more!

I made a thread on E2EE discord and it seems like players are excited about new fishing options. I think this features will definitely make E2EE better and will wait for you to fix server issue! 😉

**Comment by ukmojb** [comment]
> Then i will wait for the fix more!
> 
> I made a thread on E2EE discord and it seems like players are excited about new fishing options. I think this features will definitely make E2EE better and will wait for you to fix server issue! 😉

Thanks for waiting! I did it, try version 0.0.9!

**Comment by Krutoy242** [comment]
Mixin error seems to be fixed, but didnt test hook on server yet.
