### ISSUE TITLE
Fish instantly disappeared (probably burned out)

### ISSUE THREAD

**Issue by Krutoy242** [ukmojb/CustomFishing#7]
Despite mod description says "The items fished out will also have temporary invincibility", they still burned out same tick as fished.

There, im fishing in lava. Sometimes item created above the lava and fished normally:
![javaw_EgxnhxabVc](https://github.com/user-attachments/assets/4110d110-62ac-4f2e-912c-561d2d937b18)

But sometimes it destroyed as fast as appears on screen (can't capture this, but can prove it if required later).

**Comment by ukmojb** [comment]
item have a tag--"health", When it returns to zero, the item will disappear,If it disappears in an instant, then the representative deals more than 1000 damage in that instant (in fact, it is not truly invincible).

**Comment by Krutoy242** [comment]
In E2EE Lava doesn't deals 1000 damage. Also, isnt this is vanilla mechanic that items burned in lava instantly?

**Comment by ukmojb** [comment]
items burned in lava instantly because items only have 5 health by default(lava damage plus fire damage is 5 health)

**Comment by ukmojb** [comment]
Try 0.1.0
